### ISSUE TITLE
Incorrect amount showed in QR code.

### ISSUE THREAD

**Issue by darentuzi** [monero-integrations/monerowp#73] opened 2018-11-24 20:17 UTC
I was testing the latest beta code (3.0) and the Qr code shows correct address and payment id but incorrect amount. For example 0.758 xmr is shown as 758 in the qr code but correctly in the _Total due:_ text.

The _Pay to_: text show 105 chars out of 106 of the integrated address.

**Comment by serhack** [comment] 2018-11-24 21:36
Hi,
QR code includes the address and the payment id. The integrated address is a string composed by the address and payment id encrypted. Both work in same way. 


The payment id will be deprecated.
There's no bug. 

Cheers,
SerHack

**Comment by darentuzi** [comment] 2018-11-25 14:42
Hi,
I understand how the integrated address works, what i mean is that the formatting of the amount was incorrect in the test.
According to http://monero.wikia.com/wiki/URI_formatting the tx_amount is a floating point (eg. 5.3 XMR instead of 5300000000000), in the test 0.758 XMR was shown as 758.

**Comment by serhack** [comment] 2018-11-25 17:18
I edited the title and I'm reopening this.

**Comment by darentuzi** [comment] 2018-11-25 18:54
Yep, amount in qr code is fixed now.

In _Pay to:_ : I get a 105 chars in length integrated address, 1 character is missing.

**Comment by darentuzi** [comment] 2018-11-26 10:41
I ran a few tests with different wallets, it seems to work fine with some and not with other. try out this one:

_mnemonic:_ 
jagged dedicated upload rafts airport itches aggravate coal vampire vector gags nurse tudor drying morsel romance point duties gels upgrade oaks revamp rated rover itches
_private view key:_ 145ea5aead065c172167967dc2e663d2a36c910a129e5107fcb6f36252c8540d
_address:_ 42Y13adskmSDDKTbzgnibf1kBMAdtawzfiDCMgsdQ55KhYqE9nqzmNbUWEKRpSEXvgCyx8PGYMkcjedvGUZbsiEwRgd8BTV

**Comment by serhack** [comment] 2018-11-26 20:18
It's very strange. We could have a bug on monero-php library. Could you provide more information about the address creation?

**Comment by darentuzi** [comment] 2018-11-26 21:08
The first wallet was a random 25 word seed created from the GUI. When you said you couldn't reproduce it I started creating and testing more wallets using https://xmr.llcoins.net/addresstests.html (seeds and creating integrated address). Out of about 7 wallets one was triggering the same bug the rest were fine. 
One more thing i noticed was that the other faulty integrated address also started with **4CE**

**Comment by Olsm** [comment] 2019-06-14 15:03
We are having the same issue, I will ask if the address started with 4CE in our case and get back to you.

**Comment by serhack** [comment] 2019-06-14 20:18
Interesting.

**Comment by Olsm** [comment] 2019-06-15 13:14
I can confirm the issue is related to what kind of address it is:

> Address starts indeed with 43C and comes from monero-gui 0.14.0

> The addresses are definitely invalid as I can not send a payment using monero-gui.

This is a serious issue for merchants who will not even know that the integrated addresses are invalid and the customer cannot pay for the order. I ask for a quick solution please.

**Comment by serhack** [comment] 2019-06-15 20:14
I confirm I'm investigating. This is my top priority for this weekend.

**Comment by serhack** [comment] 2019-06-16 08:13
It should be fixed with the latest commit. Please confirm and then I'll upload the new version to Wordpress plugin directory.

**Comment by Olsm** [comment] 2019-06-19 12:05
Yes, I tested it and it is fixed. However there is a new PHP warning when generating the address due to unnecessary "use Exception":
`Warning: The use statement with non-compound name 'Exception' has no effect in C:\laragon\www\CryptoWoo\wp-content\plugins\cryptowoo-monero-addon\includes\monerowp\include\class-monero-base58.php on line 29`

But that is an issue from the library you are using I see:
https://github.com/monero-integrations/monerophp/blob/master/src/base58.php

**Comment by serhack** [comment] 2019-06-19 19:52
Thank you @Olsm @darentuzi

**Closed by serhack** 2019-06-19 19:52 UTC
Labels: bug
